### PR TITLE
fixes PSR-4 autoloading standard and view publishing

### LINKED ISSUE #5: Unable to install (does not comply with psr-4 autoloading standard)
image

### PR DESCRIPTION
**Pull request by pryley**
I have kept your original (non-standard) code indentation preferences and style.

Fixes #5

### CODE REVIEW

File: src/ServiceProvider.php [hunk 1]
```diff
@@ -5,6 +5,9 @@
 use Statamic\Providers\AddonServiceProvider;
 
 class ServiceProvider extends AddonServiceProvider {
+
+  protected $publishAfterInstall = false;
```
Comment (jcohlmeyer) [inline src/ServiceProvider.php]: Hey, just wondering why you have added this line, I think publishing after install is desired is it not?

Comment (pryley) [reply src/ServiceProvider.php]: Oh, I added it since you had the instructions in the README for manually publishing them. But yes, it's not needed.

Comment (jcohlmeyer) [reply src/ServiceProvider.php]: Ya. They were added to the readme before Statamic auto published on install. I have removed this step from the install part of the readme. Thanks.
